I = imread('cameraman.tif');
PSF = fspecial('motion', 5, 45);
bi = edgetaper(I, PSF);
BlurredImage = imfilter(bi, PSF);
guess = GeneticAlgorithm(10, 2, 10, 0.1, 0.1, 0.5, @CostFunction, I, BlurredImage);
PSF1 = fspecial('motion', 20 * guess.var(1) + 1, 90 * guess.var(2));
[n1, n2] = size(PSF1);
PSF_pred = zeros(n1 + 2, n2 + 2);
PSF_pred(2: end -1, 2: end - 1) = PSF1;
newBlurred = edgetaper(BlurredImage, PSF_pred);
PredictedImage = deconvlucy(newBlurred, PSF_pred, 10);
subplot(221);imshow(BlurredImage);
title('A = Blurred and Noisy');
subplot(222);imshow(PSF,[]);
title('True PSF');
subplot(223);imshow(PredictedImage);
title('Deblurred Image');
subplot(224);imshow(PSF_pred,[]);
title('Guesses PSF');